{
 "title": "Aya Testnet Stats",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "chain_id",
    "label": "Chain ID",
    "query": {
     "query": "label_values(tendermint_consensus_height, chain_id)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(tendermint_consensus_height{chain_id=\"$chain_id\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$chain_id",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ayad Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{alias=\"aya\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ayad_stats_jailed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Validator Caught Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ayad_stats_catchingup", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Voting Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ayad_stats_votingpower", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "System Health",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\",alias=\"relay1-host\"}[1m])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"relay1-host\"} / (node_memory_MemTotal_bytes{alias=\"relay1-host\"})))* 100",
     "legendFormat": "RAM"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{alias=\"relay1-host\"} / node_memory_SwapTotal_bytes{alias=\"relay1-host\"})) * 100",
     "legendFormat": "SWAP"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"relay1-host\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"relay1-host\"})",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_validators{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "tendermint_consensus_missing_validators{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "tendermint_consensus_byzantine_validators{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Byzantine"
    }
   ]
  },
  {
   "title": "Voting Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Online"
    },
    {
     "expr": "tendermint_consensus_missing_validators_power{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "tendermint_consensus_byzantine_validators_power{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Byzantine"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ayad_stats_uptime / 3600", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Block Height - Network",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_latest_block_height{chain_id=\"$chain_id\"}"
    }
   ]
  },
  {
   "title": "Current Block Height - Validator",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_latest_block_height{chain_id=\"$chain_id\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Avg Block Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_block_interval_seconds_sum / tendermint_consensus_block_interval_seconds_count"
    }
   ]
  },
  {
   "title": "Active Validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tendermint_p2p_peers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_total_txs{chain_id=\"$chain_id\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Failed Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_mempool_failed_txs{chain_id=\"$chain_id\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Bonded Tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power{chain_id=\"$chain_id\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Unconfirmed Txs",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "tendermint_mempool_size{chain_id=\"$chain_id\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total EN's",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ayad_stats_totalen", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "EN's Jailed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ayad_stats_totaljailed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "EN's Tombstoned",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ayad_stats_tombstoned", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 10 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{instance=\"127.0.0.1:26660\"}/(1024*1024)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Processor usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\", alias=\"relay1-host\"}[1m])) * 100)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_block_size_bytes{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Block Size"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_num_txs{chain_id=\"$chain_id\", instance=\"$instance\"}",
     "legendFormat": "Transactions"
    }
   ]
  }
 ]
}